services:
  yt-dlp-host:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - yt-dlp-jsons:/app/data/jsons
    environment:
      - FLASK_APP=src.server:app
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - DOWNLOAD_DIR=/app/data/downloads
      - TASKS_FILE=/tmp/tasks.json
      - KEYS_FILE=/app/data/jsons/api_keys.json
      - ADMIN_API_KEY=${ADMIN_API_KEY:-}
      - COOKIES_B64=${COOKIES_B64:-}
    restart: unless-stopped

    networks:
      - dokploy-network

volumes:
  yt-dlp-jsons:

networks:
  dokploy-network:
    external: true