services:
  yt-dlp-host:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/data/downloads
      - ./jsons:/app/data/jsons
    env_file:
      - .env
    environment:
      - FLASK_APP=src.server:app
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - DOWNLOAD_DIR=/app/data/downloads
      - TASKS_FILE=/tmp/tasks.json
      - KEYS_FILE=/app/data/jsons/api_keys.json
    restart: unless-stopped
